# Labels based on file paths
# See: https://github.com/actions/labeler

api:
  - changed-files:
      - any-glob-to-any-file:
          - apps/api/**

web:
  - changed-files:
      - any-glob-to-any-file:
          - apps/web/**

k8s:
  - changed-files:
      - any-glob-to-any-file:
          - k8s/**

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Dockerfile"
          - docker-compose.yml

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - docs/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"
          - "**/package-lock.json"
          - "**/pyproject.toml"
          - "**/uv.lock"
          - "**/requirements*.txt"

database:
  - changed-files:
      - any-glob-to-any-file:
          - apps/api/migrations/**
          - apps/api/src/models/**

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "**/tests/**"
          - "**/__tests__/**"
          - "**/*.test.*"
          - "**/*.spec.*"
